language: python
addons:
  ssh_known_hosts: pycones.prod.aws.apsl.io:2232
script:
- date
before_deploy:
  - openssl aes-256-cbc -K $encrypted_40f7cf1e888b_key -iv $encrypted_40f7cf1e888b_iv -in deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: ssh -p 2232 pycones20@pycones.prod.aws.apsl.io "cd web-pycones; git pull origin 2020; ./deploy/deploy.sh;"
  on:
    branch: 2020

