language: python
addons:
    ssh_known_hosts: pycones.prod.aws.apsl.io:2232

before_deploy:
    - openssl aes-256-cbc -K $encrypted_52ffc47aa7ea_key -iv $encrypted_52ffc47aa7ea_iv -in deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa
script:
    - date
deploy:
    provider: script
    skip_cleanup: true
    script: ssh -p 2232 pycones20@pycones.prod.aws.apsl.io "cd web-pycones; git pull origin 2020; ./deploy/deploy.sh;"
    on:
        branch: 2020
