version: '3'

volumes:
  db-data:
    driver: local
  node_modules:
    driver: local

services:

  # Database service.
  db:
    image: postgres:9.6
    container_name: pycones-db
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: potato
      POSTGRES_DB: pycones2020

  web:
    build: .
    image: pycones
    depends_on:
      - db
    volumes:
     - ./src:/app
    environment:
      DJANGO_SECRET_KEY: 'oluyomahB3vaaw0iemahCh8Eighai7Ai'
      DJANGO_SETTINGS_MODULE: 'config.settings.local'
      DJANGO_ALLOWED_HOSTS: '*'
      DATABASE_URL: 'postgres://postgres:potato@db:5432/pycones2020'
    ports:
      - "8000:8000"
    command: run-devel

